### ISSUE TITLE
Trainer resistance gets stuck repeatedly in Zwift

### ISSUE THREAD

**Issue by Schwizzle** [kinetic-fit/firmware#1]
The issue is already being discussed in the Zwift forums: https://forums.zwift.com/t/kurt-kinetic-smart-control-resistance-sticks-at-top-of-hill-in-free-ride/14231 

- The phenomenon occurs after somewhere in between 25-40 minutes into the ride. Resistance won't change anymore, mostly gets stuck near the highest possible resistance
- Unplugging and replugging, then reconnecting to Zwift via the game menu helps for a minute, then resistance gets stuck again very quickly
- Trainer won't connect to fit app after ending Zwift, too. LED is off but trainer is humming when unplugging and replugging it
- occurs when connecting via companion app or directly via laptop, with or without other BLE connections present
- I use an external powermeter as power source (ANT+)

Thanks for looking into the issue, this makes the trainer mostly unusable for Zwift.

**Comment by netizen01** [comment]
Hi Schwizzle - your description of the issue is a hardware issue, specifically the carriage motor.
